title: "Transformers Interactive Neural Network Visualizer"
description: "Interactive tool for visualizing an artificial neural network, illustrating data flow from the input layer through hidden layers to the output layer."
theme: jekyll-theme-minimal
include: [".nojekyll", "*.html", "*.md", "docs/"]
exclude: ["README.md"]
plugins:
  - jekyll-sitemap
